### ISSUE TITLE
无法理解状态c

### ISSUE THREAD

**Issue by Bug-terminator** [Alicesla/Open-source-project-team_2020#6]
今天的前两个题解中状态c有点难理解, 希望理解的同学详细解释一下, 感谢.

**Comment by YuRui997** [comment]
同学你好，我的理解是这样的：状态c的引入是为了能够找到一个递归关系。状态a和状态b都是在研究当前节点的状态（放还是不放摄像头），c就把问题引向了当前节点的两颗子树，对于 c 而言，要保证两棵子树被完全覆盖，要么在root 处放置一个摄像头，需要的摄像头数目为 a；要么 root 处不放置摄像头，此时两棵子树分别保证自己被覆盖，需要的摄像头数目为 l_b + r_b.这样就把整个问题联系在了一起，通过返回b的值，即为所求。欢迎继续提问~~~~

​	
 +r 
b
​	
 。

**Comment by Bug-terminator** [comment]
问题已解决
