### ISSUE TITLE
空结点的状态a为什么要用一个大数

### ISSUE THREAD

**Issue by Bug-terminator** [Alicesla/Open-source-project-team_2020#7]
按照状态a的定义:root 必须放置摄像头的情况下，覆盖整棵树需要的摄像头数目。 空结点应该为0, 希望理解的同学解释一下,感谢.

**Comment by YuRui997** [comment]
同学你好，对于这个我的理解是不透彻的，我大概说一下我认为的代码编写者的用意：因为root为当前节点时，它所对应的子节点可能一个或者两个都为空，此时要想监控到root，只有两种办法，要么在root处放置摄像头，要么在那个不空的孩子节点处放置摄像头，因此这种状态下必须通过一个大数来辨识出那个为空的子节点，以此提醒整个递归，为空的那条路上放置摄像头是行不通的。欢迎继续补充~~~~~~

**Comment by Bug-terminator** [comment]
问题已解决
