### ISSUE TITLE
2020.09.22第二个题解疑问

### ISSUE THREAD

**Issue by Alicesla** [Alicesla/Open-source-project-team_2020#8]
不明白和为什么看和root的关系，abc代表的都不太清楚

**Comment by YuRui997** [comment]
你好，我的理解是这样的：root指的是当前节点，不一定是整棵树的根节点。root代表递归到的那一步所对应的树的根节点。a,b,c的定义我是这样理解的：a指的是当前节点有摄像头后要覆盖以root为根的那棵树所需要的摄像头总数，b指的是不管当前root是否有摄像头要覆盖以root为根的整棵树需要的摄像头数，c的作用就是为了引出递归条件，把问题由当前root引向它所指向的子树，通过定义覆盖两棵子树需要的摄像头数目，无论节点 root 本身是否被监控到，可以推出c = min(a, lb + rb)。
 欢迎继续提问~~~~~~~~~

**Comment by Bug-terminator** [comment]
问题已解决
